<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Broiler.Plate</RootNamespace>
    <AssemblyName>Broiler.Plate.Core</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Broiler.Plate.Windows" />
    <InternalsVisibleTo Include="Broiler.Plate.Windows.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Broiler.Documents.Docx" />
    <PackageReference Include="Broiler.Documents.Html" />
    <PackageReference Include="Broiler.Documents.Markdown" />
    <PackageReference Include="Broiler.Documents.Model" />
    <PackageReference Include="Broiler.Documents.Rtf" />
    <PackageReference Include="Broiler.Graphics" />
    <PackageReference Include="Broiler.Input.Keyboard" />
    <PackageReference Include="Broiler.UI.AboutDialog" />
    <PackageReference Include="Broiler.UI.AboutDialog.Standard" />
    <PackageReference Include="Broiler.UI.Dialog.Standard" />
    <PackageReference Include="Broiler.UI.FileDialog.Standard" />
    <PackageReference Include="Broiler.UI.ImageView.Standard" />
    <PackageReference Include="Broiler.UI.Label.Standard" />
    <PackageReference Include="Broiler.UI.Menu.Standard" />
    <PackageReference Include="Broiler.UI.RichEdit.Standard" />
    <PackageReference Include="Broiler.UI.Toolbar.Standard" />
    <PackageReference Include="Broiler.UI.Window.Standard" />
  </ItemGroup>

</Project>
